from .base import *
from .mf_age  import *
from .mf_ca import *
from .mf_chol import *
from .mf_cp import *
from .mf_exang import *
from .mf_fbs import *
from .mf_oldpeak import *
from .mf_restach import *
from .mf_sex import *
from .mf_slope import *
from .mf_thal import *
from .mf_thalach import *
from .mf_trestbps import *